logLevel: info

srt: false
rtmp: false
moq: false

rtsp: true
rtspAddress: :8554

hls: false

webrtc: true
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189

paths:
  vision:
    source: udp+mpegts://127.0.0.1:8891
